Repository Col-E/Recaf, pull requests merged in 2022-01, with the labels that each got.

#443 Fix potential file handle leak from zip CRC logic backport
  pom.xml
  src/main/java/me/coley/recaf/Recaf.java
  src/main/java/me/coley/recaf/workspace/JarResource.java
Labels: bug

#445 Replace Desktop#browse
  checkstyle-suppressions.xml
  src/main/java/me/coley/recaf/command/impl/Initializer.java
  src/main/java/me/coley/recaf/ui/MainMenu.java
  src/main/java/me/coley/recaf/ui/controls/ExceptionAlert.java
  src/main/java/me/coley/recaf/ui/controls/pane/ContactInfoPane.java
  src/main/java/me/coley/recaf/ui/controls/pane/SysInfoPane.java
  src/main/java/me/coley/recaf/util/UiUtil.java
Labels: enhancement

#447 Return class header detection back & some fixes
  src/main/java/me/coley/recaf/util/ClassUtil.java
  src/main/java/me/coley/recaf/util/IOUtil.java
  src/main/java/me/coley/recaf/workspace/JarResource.java
Labels: bug

#450 Allow export of multiple zip entries with the same name
  src/main/java/me/coley/recaf/command/impl/Export.java
  src/main/java/me/coley/recaf/util/VMUtil.java
Labels: bug, enhancement

#449 Add in-memory classpath for javac
  src/main/java/me/coley/recaf/command/impl/LoadWorkspace.java
  src/main/java/me/coley/recaf/compiler/JavacCompiler.java
  src/main/java/me/coley/recaf/compiler/JavacTargetVersion.java
  src/main/java/me/coley/recaf/compiler/ResourceVirtualJavaFileObject.java
  src/main/java/me/coley/recaf/control/gui/GuiController.java
  src/main/java/me/coley/recaf/ui/controls/text/JavaEditorPane.java
  src/main/java/me/coley/recaf/workspace/Workspace.java
Labels: enhancement

#462 Get rid of direct unsafe reference
  recaf-ui/build.gradle
  recaf-ui/src/main/java/me/coley/recaf/util/JigsawUtil.java
Labels: enhancement, 3.X

#463 User language config
  recaf-ui/src/main/java/me/coley/recaf/config/ConfigRegistry.java
  recaf-ui/src/main/java/me/coley/recaf/config/container/DisplayConfig.java
  recaf-ui/src/main/java/me/coley/recaf/presentation/GuiPresentation.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/config/ConfigLanguage.java
  recaf-ui/src/main/java/me/coley/recaf/ui/pane/ConfigPane.java
  recaf-ui/src/main/java/me/coley/recaf/ui/util/Lang.java
  recaf-ui/src/main/resources/translations/de_DE.lang
  recaf-ui/src/main/resources/translations/en.lang
  recaf-ui/src/main/resources/translations/zh_CN.lang
  recaf-utils/src/main/java/me/coley/recaf/util/InternalPath.java
  recaf-utils/src/main/java/me/coley/recaf/util/SelfReferenceUtil.java
Labels: enhancement, 3.X

#466 Optimize resource loading & bring back in-memory classpath for the compiler
  recaf-core/src/main/java/me/coley/recaf/compile/Compiler.java
  recaf-core/src/main/java/me/coley/recaf/compile/javac/JavacCompiler.java
  recaf-core/src/main/java/me/coley/recaf/compile/javac/VirtualFileManager.java
  recaf-core/src/main/java/me/coley/recaf/util/Directories.java
  recaf-core/src/main/java/me/coley/recaf/util/visitor/ValidationClassReader.java
  recaf-core/src/main/java/me/coley/recaf/workspace/resource/ClassPatchingListener.java
  recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/ApkContentSource.java
  recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/ArchiveFileContentSource.java
  recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/ContainerContentSource.java
  recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/DirectoryContentSource.java
  recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/FileContentSource.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/code/java/JavaArea.java
  recaf-ui/src/main/java/me/coley/recaf/util/CompileDependencyUpdater.java
Labels: enhancement

#465 Dynamically update language in UI without restart
  recaf-ui/src/main/java/me/coley/recaf/config/ConfigContainer.java
  recaf-ui/src/main/java/me/coley/recaf/config/container/DisplayConfig.java
  recaf-ui/src/main/java/me/coley/recaf/ui/ClassView.java
  recaf-ui/src/main/java/me/coley/recaf/ui/ClassViewMode.java
  recaf-ui/src/main/java/me/coley/recaf/ui/FileViewMode.java
  recaf-ui/src/main/java/me/coley/recaf/ui/context/ClassContextBuilder.java
  recaf-ui/src/main/java/me/coley/recaf/ui/context/DirectoryContextBuilder.java
  recaf-ui/src/main/java/me/coley/recaf/ui/context/FieldContextBuilder.java
  recaf-ui/src/main/java/me/coley/recaf/ui/context/FileContextBuilder.java
  recaf-ui/src/main/java/me/coley/recaf/ui/context/MethodContextBuilder.java
  recaf-ui/src/main/java/me/coley/recaf/ui/context/PackageContextBuilder.java
  recaf-ui/src/main/java/me/coley/recaf/ui/context/ResourceContextBuilder.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/ActionButton.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/EnumComboBox.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/SubLabeled.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/config/ConfigBinding.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/config/ConfigBoolean.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/config/ConfigLanguage.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/hex/HexView.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/menu/ActionMenu.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/menu/ActionMenuItem.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/tree/WorkspaceCell.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/tree/item/DummyItem.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/tree/item/WorkspaceRootItem.java
  recaf-ui/src/main/java/me/coley/recaf/ui/dialog/ConfirmDialog.java
  recaf-ui/src/main/java/me/coley/recaf/ui/dialog/DirectorySelectDialog.java
  recaf-ui/src/main/java/me/coley/recaf/ui/dialog/PackageSelectDialog.java
  recaf-ui/src/main/java/me/coley/recaf/ui/dialog/TextInputDialog.java
  recaf-ui/src/main/java/me/coley/recaf/ui/dialog/Wizard.java
  recaf-ui/src/main/java/me/coley/recaf/ui/dialog/WizardDialog.java
  recaf-ui/src/main/java/me/coley/recaf/ui/pane/ConfigPane.java
  recaf-ui/src/main/java/me/coley/recaf/ui/pane/DockingRootPane.java
  recaf-ui/src/main/java/me/coley/recaf/ui/pane/DockingWrapperPane.java
  recaf-ui/src/main/java/me/coley/recaf/ui/pane/HierarchyPane.java
  recaf-ui/src/main/java/me/coley/recaf/ui/pane/InfoPane.java
  recaf-ui/src/main/java/me/coley/recaf/ui/pane/OutlinePane.java
  recaf-ui/src/main/java/me/coley/recaf/ui/pane/SearchPane.java
  recaf-ui/src/main/java/me/coley/recaf/ui/pane/WelcomePane.java
  recaf-ui/src/main/java/me/coley/recaf/ui/pane/WorkspaceButtonsPane.java
  recaf-ui/src/main/java/me/coley/recaf/ui/pane/assembler/AssemblerPane.java
  recaf-ui/src/main/java/me/coley/recaf/ui/pane/assembler/VariableTable.java
  recaf-ui/src/main/java/me/coley/recaf/ui/prompt/QuickNavPrompt.java
  recaf-ui/src/main/java/me/coley/recaf/ui/prompt/WorkspaceClosePrompt.java
  recaf-ui/src/main/java/me/coley/recaf/ui/prompt/WorkspaceDropPrompts.java
  recaf-ui/src/main/java/me/coley/recaf/ui/prompt/WorkspaceIOPrompts.java
  recaf-ui/src/main/java/me/coley/recaf/ui/util/CellFactory.java
  recaf-ui/src/main/java/me/coley/recaf/ui/util/Lang.java
  recaf-ui/src/main/java/me/coley/recaf/ui/util/Menus.java
  recaf-ui/src/main/java/me/coley/recaf/ui/window/MainMenu.java
  recaf-ui/src/main/java/me/coley/recaf/ui/window/MainWindow.java
  recaf-ui/src/main/java/me/coley/recaf/util/Translatable.java
Labels: enhancement

#464 System language defaulting
  recaf-ui/src/main/java/me/coley/recaf/RecafUI.java
  recaf-ui/src/main/java/me/coley/recaf/config/container/DisplayConfig.java
  recaf-ui/src/main/java/me/coley/recaf/ui/util/Lang.java
  recaf-ui/src/main/resources/translations/en_US.lang
Labels: enhancement, 3.X

#458 Move to Github Actions
  .drone.yml
  .github/workflows/build.yml
Labels: enhancement

#469 Czech translation for 3.x
  recaf-ui/src/main/resources/translations/cs_CZ.lang
Labels: enhancement, 3.X

#471 Fix test results not being shown on prs from forks
  .github/workflows/build.yml
  .github/workflows/display_test_results.yml
Labels: enhancement, 3.X

#470 Fixes mappings throwing error
  recaf-core/src/main/java/me/coley/recaf/mapping/MappingsAdapter.java
  recaf-core/src/main/java/me/coley/recaf/mapping/impl/SimpleMappings.java
  recaf-core/src/main/java/me/coley/recaf/mapping/impl/TinyV1Mappings.java
Labels: bug, 3.X
