Repository Col-E/Recaf, pull requests merged in 2022-08, with the labels that each got.

#572 fix: update czech translation
  recaf-ui/src/main/resources/translations/cs_CZ.lang
Labels: enhancement, 3.X

#575 Fix ComboBox translation not updating when changing language
  recaf-ui/src/main/java/me/coley/recaf/ui/control/EnumComboBox.java
  recaf-ui/src/main/java/me/coley/recaf/ui/control/config/ConfigEnum.java
Labels: enhancement, 3.X

#591 Introduce "itf" suffix to invokestatic calls
  src/main/java/me/coley/recaf/parse/bytecode/Disassembler.java
  src/main/java/me/coley/recaf/parse/bytecode/ast/ItfAST.java
  src/main/java/me/coley/recaf/parse/bytecode/ast/MethodInsnAST.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/MethodInsnParser.java
  src/test/java/me/coley/recaf/AssemblyAstTest.java
  src/test/java/me/coley/recaf/AssemblyCasesTest.java
Labels: enhancement, 2.X

#592 More support for itf aware instructions
  recaf-assembler/build.gradle
  recaf-assembler/src/main/java/me/coley/recaf/assemble/ast/insn/MethodInstruction.java
  recaf-assembler/src/main/java/me/coley/recaf/assemble/transformer/AstToMethodTransformer.java
  recaf-assembler/src/main/java/me/coley/recaf/assemble/transformer/BytecodeToAstTransformer.java
  recaf-assembler/src/main/java/me/coley/recaf/assemble/transformer/JasmToAstTransformer.java
  recaf-ui/src/main/resources/languages/bytecode.json
Labels: enhancement, 3.X

#588 Add zh-cn translations to dev3
  recaf-ui/src/main/resources/translations/zh_CN.lang
Labels: enhancement, 3.X

#587 Add new zh-cn translations and optimize old translations
  src/main/resources/translations/zh-cn.json
Labels: enhancement, 2.X

#596 Blinking no more in workspace outline for files and classes
  recaf-core/src/main/java/me/coley/recaf/code/FileInfo.java
  recaf-core/src/main/java/me/coley/recaf/search/query/TextQuery.java
  recaf-ui/src/main/java/me/coley/recaf/ui/FileView.java
  recaf-ui/src/main/java/me/coley/recaf/ui/pane/DiffViewPane.java
  recaf-ui/src/main/java/me/coley/recaf/ui/util/CellFactory.java
  recaf-ui/src/main/java/me/coley/recaf/ui/util/Icons.java
Labels: bug, 3.X
