Repository Col-E/Recaf, pull requests merged in 2024-01, with the labels that each got.

#756 fix: infinite loading on launch
  src/main/java/me/coley/recaf/Recaf.java
Labels: bug, 3rd party problem, 2.X

#757 fix: Fixed misspelling of "parameters" in some instruction parsers
  src/main/java/me/coley/recaf/parse/bytecode/parser/AliasDeclarationParser.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/HandleParser.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/IincInsnParser.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/IntInsnParser.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/InvokeDynamicParser.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/JumpInsnParser.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/LineInsnParser.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/LookupSwitchInsnParser.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/MethodInsnParser.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/MultiArrayParser.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/SignatureParser.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/TableSwitchInsnParser.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/TypeInsnParser.java
  src/main/java/me/coley/recaf/parse/bytecode/parser/VarInsnParser.java
Labels: enhancement, 2.X

#759 Add VineFlower decompiler and refactor DecompilerResult and JvmDecompiler
  dependencies.gradle
  recaf-core/build.gradle
  recaf-core/src/main/java/software/coley/recaf/config/ConfigGroups.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/AbstractDecompiler.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/AbstractJvmDecompiler.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/BaseDecompilerConfig.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/DecompileResult.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/Decompiler.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/DecompilerConfig.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/DecompilerManager.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/JvmDecompiler.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/NoopAndroidDecompiler.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/NoopDecompilerConfig.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/NoopJvmDecompiler.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/cfr/CfrConfig.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/cfr/CfrDecompiler.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/procyon/ProcyonConfig.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/procyon/ProcyonDecompiler.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/vineflower/BaseSource.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/vineflower/ClassSource.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/vineflower/DecompiledOutputSink.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/vineflower/DummyResultSaver.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/vineflower/LibrarySource.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/vineflower/VineflowerConfig.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/vineflower/VineflowerDecompiler.java
  recaf-core/src/main/java/software/coley/recaf/services/decompile/vineflower/VineflowerLogger.java
  recaf-core/src/test/java/software/coley/recaf/services/decompile/DecompileManagerTest.java
  recaf-ui/src/main/java/software/coley/recaf/services/config/ConfigIconManager.java
  recaf-ui/src/main/java/software/coley/recaf/ui/pane/ConfigPane.java
  recaf-ui/src/main/java/software/coley/recaf/ui/pane/editing/AbstractDecompilePane.java
  recaf-ui/src/main/java/software/coley/recaf/ui/pane/editing/jvm/JvmDecompilerPane.java
  recaf-ui/src/main/resources/translations/en_US.lang
Labels: enhancement, 4.X
